spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///blog
    username: root
    password: root
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main #设置重启的目录
#      exclude: static #设置不重启的目录
mybatis:
  type-aliases-package: com.example.model
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  check-config-location: true
logging:
  level: debug
